config/routes.rb
Ksat::Application.routes.draw do
  resources :ksat_lists do
    resources :task_items do
      member do
        patch :complete
      end
    end
  end
  root 'ksat_lists#index'

end

app/models/ksat_list.rb
class KsatList < ActiveRecord::Base
	has_many :task_items

	validates :title, presence: true
	validates :title, length: { minimum: 3 }
	validates :description, presence: true
	validates :description, length: { minimum: 5 }
end

app/models/task_item.rb
class TaskItem < ActiveRecord::Base
  belongs_to :ksat_list

  validates :content, presence: true,
  					  length: { minimum: 2 }

  def completed?
  	!completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ksat_lists_controller.rb
class KsatListsController < ApplicationController
  before_action :set_ksat_list, only: [:show, :edit, :update, :destroy]

  # GET /ksat_lists
  # GET /ksat_lists.json
  def index
    @ksat_lists = KsatList.all
  end

  # GET /ksat_lists/1
  # GET /ksat_lists/1.json
  def show
  end

  # GET /ksat_lists/new
  def new
    @ksat_list = KsatList.new
  end

  # GET /ksat_lists/1/edit
  def edit
  end

  # POST /ksat_lists
  # POST /ksat_lists.json
  def create
    @ksat_list = KsatList.new(ksat_list_params)

    respond_to do |format|
      if @ksat_list.save
        format.html { redirect_to @ksat_list, notice: 'Ksat list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ksat_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @ksat_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ksat_lists/1
  # PATCH/PUT /ksat_lists/1.json
  def update
    respond_to do |format|
      if @ksat_list.update(ksat_list_params)
        format.html { redirect_to @ksat_list, notice: 'Ksat list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ksat_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ksat_lists/1
  # DELETE /ksat_lists/1.json
  def destroy
    @ksat_list.destroy
    respond_to do |format|
      format.html { redirect_to ksat_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ksat_list
      @ksat_list = KsatList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ksat_list_params
      params.require(:ksat_list).permit(:title, :description)
    end
end

app/controllers/task_items_controller.rb
class TaskItemsController < ApplicationController
  before_action :find_ksat_list

  def index
  end

  def new
  	@task_item = @ksat_list.task_items.new
  end

  def create
  	@task_item = @ksat_list.task_items.new(task_item_params)
  	if @task_item.save
  		flash[:success] = "Added task list item."
  		redirect_to ksat_list_task_items_path
  	else
  		flash[:error] = "There was a problem adding that task list item."
  		render action: :new
  	end
  end

  def edit
    @task_item = @ksat_list.task_items.find(params[:id])
  end

  def update
    @task_item = @ksat_list.task_items.find(params[:id])
    if @task_item.update_attributes(task_item_params)
      flash[:success] = "Saved task list item."
      redirect_to ksat_list_task_items_path
    else
      flash[:error] = "That task item could not be saved."
      render action: :edit
    end
  end

  def destroy
    @task_item = @ksat_list.task_items.find(params[:id])
    if @task_item.destroy
      flash[:success] = "Task list item was successfully deleted."
    else
      flash[:error] = "Task list item couldn't be deleted."
    end
    redirect_to ksat_list_task_items_path
  end

  def complete
    @task_item = @ksat_list.task_items.find(params[:id])
    @task_item.update_attribute(:completed_at, Time.now)
    redirect_to ksat_list_task_items_path, notice: "Task item successfully marked as complete."
  end

  def url_options
    { ksat_list_id: params[:ksat_list_id] }.merge(super)
  end

  private
  def find_ksat_list
    @ksat_list = KsatList.find(params[:ksat_list_id])
  end

  def task_item_params
  	params[:task_item].permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ksat_lists_helper.rb
module KsatListsHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/views/ksat_lists/_form.html.erb
<%= form_for(@ksat_list) do |f| %>

<% if @ksat_list.errors.any? %>
<div class="ui error message">
  <div class="header">
    <%= pluralize(@ksat_list.errors.count, "error") %> prohibited this ksat_list from being saved:
  </div>
  <ul class="list">
    <% @ksat_list.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="ui form segment">
  <div class="field">
    <%= f.label :title %>
    <div class="ui left labeled icon input">
      <%= f.text_field :title %>
      <i class="flag icon"></i>
      <div class="ui corner label">
        <i class="icon asterisk"></i>
      </div>
    </div>
  </div>
  <div class="field">
    <%= f.label :description %>
    <div class="ui left labeled icon input">
      <%= f.text_area :description %>
      <div class="ui corner label">
        <i class="icon asterisk"></i>
      </div>
    </div>
  </div>
  <%= f.submit class: "ui blue submit button tiny" %>
</div>

<% end %>

  

app/views/ksat_lists/edit.html.erb
<h2 class="ui header">
	Editing ksat_list
	<div class="sub header">Manage your account settings and set e-mail preferences.</div>
</h2>

<div class="ui buttons">
	<%= link_to 'Show', @ksat_list, class: "tiny ui teal button" %>
	<%= link_to 'Back', ksat_lists_path, class: "tiny ui teal button" %>
</div>

<%= render 'form' %>

app/views/ksat_lists/index.html.erb
<h2 class="ui header">
  Task List
  <div class="sub header">
    Manage your task list and set your sub-task list.
  </div>
</h2>

<div class="ui divider"></div>

<table class="ui three column table segment">
  <thead>
    <tr>
      <th class="five wide">Title</th>
      <th class="six wide">Description</th>
      <th class="five wide">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @ksat_lists.each do |ksat_list| %>
      <tr id="<%= dom_id(ksat_list) %>">
        <td><%= ksat_list.title %></td>
        <td><%= ksat_list.description %></td>
        <td>
          <div class="ui buttons">
            <%= link_to '<i class="list layout icon"></i> List Items'.html_safe, ksat_list_task_items_path(ksat_list), class: "tiny ui button" %>
            <%= link_to '<i class="bullseye icon"></i> Show'.html_safe, ksat_list, class: "tiny ui button" %>
            <%= link_to '<i class="edit icon"></i> Edit'.html_safe, edit_ksat_list_path(ksat_list), class: "tiny ui button" %>
            <%= link_to '<i class="remove icon"></i> Delete'.html_safe, ksat_list, class: "tiny ui red button delete" , method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <th colspan="3">
        <%= link_to '<i class="add sign box icon"></i>' 'New Ksat list'.html_safe, new_ksat_list_path, class: "tiny ui teal button" %>
      </th>
    </tr>
  </tfoot>
</table>

app/views/ksat_lists/new.html.erb
<h2 class="ui header">
	New ksat_list
	<div class="sub header">Manage your account settings and set e-mail preferences.</div>
</h2>
<%= link_to 'Back', ksat_lists_path, class: "tiny ui teal button" %>

<%= render 'form' %>

app/views/ksat_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ksat_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ksat_list.description %>
</p>

<div class="ui buttons">
	<%= link_to 'Edit', edit_ksat_list_path(@ksat_list), class: "tiny ui teal button" %>
	<%= link_to 'Back', ksat_lists_path, class: "tiny ui teal button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ksat</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="ui small inverted menu">
  <%= link_to '<i class="home icon"></i> Home'.html_safe, root_path, class: "active item" %>
  <%= link_to '<i class="briefcase icon"></i> Task Lists'.html_safe, ksat_lists_path, class: "item" %>
  <div class="right menu">
    <div class="ui dropdown item">
      Language <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item">English</a>
        <a class="item">Russian</a>
        <a class="item">Spanish</a>
      </div>
    </div>
    <div class="ui mini buttons">
      <div class="item">
        <div class="ui blue button">
          <i class="key icon"></i>
          Log In
        </div>
        <div class="ui green button">
          <i class="user icon"></i>
          Sign Up
        </div>
      </div>
    </div>
  </div>
</div>

	<% flash.each do |type, message| %>
	<div class="alert flash <%= type %>">
		<%= message %>	
	</div>
	<% end %>

<%= yield %>

</body>
</html>

app/views/task_items/_form.html.erb
<% if @task_item.errors.any? %>
<div class="ui error message">
  <div class="header">
		<%= pluralize(@task_item.errors.count, "error") %> prohibited this task item from being saved:
	</div>
	<ul class="list">
    <% @task_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="ui form segment">
  <div class="field">
		<%= form.label :content %>
		<div class="ui left labeled icon input">
			<%= form.text_field :content %>
			<i class="user icon"></i>
	    <div class="ui corner label">
	      <i class="icon asterisk"></i>
	    </div>
	  </div>
	</div>
  <%= form.submit "Save", class: "ui blue submit button tiny" %>
</div>

app/views/task_items/edit.html.erb
<h2 class="ui header">
	<%= @ksat_list.title %> - Editing Task List Item
	<div class="sub header">
		<%= @ksat_list.description %>
	</div>
</h2>

<%= form_for [@ksat_list, @task_item] do |form| %>
  <%= render partial: form %>
<% end %>

app/views/task_items/index.html.erb
<h2 class="ui header">
	<%= @ksat_list.title %>
	<div class="sub header">
		<%= @ksat_list.description %>
	</div>
</h2>

<div class="ui divider"></div>

<table class="task_items ui three column table segment">
  <thead>
    <tr>
      <th class="three wide">Completed?</th>
      <th class="eight wide">Content</th>
      <th class="five wide">Action</th>
    </tr>
  </thead>

  <tbody>
  	<% @ksat_list.task_items.each do |task_item| %>
			<tr class="task_items" id="<%= dom_id(task_item) %>">
				<td>
					<% if task_item.completed? %>
						<%= task_item.completed_at %>			
					<% else %>
						<%= link_to "Mark as Complete", complete_ksat_list_task_item_path(task_item), class: "tiny ui button", method: :patch %>
					<% end %>
				</td>
				<td>
					<%= task_item.content %>
				</td>
				<td>
					<div class="ui buttons">
						<%= link_to '<i class="edit icon"></i> Edit'.html_safe, edit_ksat_list_task_item_path(task_item), class: "tiny ui button" %>
						<%= link_to '<i class="remove icon delete"></i> Delete'.html_safe, ksat_list_task_item_path(task_item), class: "tiny ui red button", method: :delete, data: { confirm: "Are you sure?" } %>
					</div>
				</td>
			</tr>
		<% end %>
  </tbody>
  <tfoot>
  	<tr>
      <th colspan="3">
      	<%= link_to '<i class="add sign box icon"></i> New Task Items'.html_safe, new_ksat_list_task_item_path, class: "tiny ui teal button" %>
      </th>
    </tr>
  </tfoot>
</table>

app/views/task_items/new.html.erb
<h2 class="ui header">
	<%= @ksat_list.title %> - Add Task List Item
	<div class="sub header">
		<%= @ksat_list.description %>
	</div>
</h2>

<%= form_for [@ksat_list, @task_item] do |form| %>
  <%= render partial: form %>
<% end %>